project:
  type: website
  
website:
  title: "Phil in the Blank"
  description: "A science and stats blog"
  sidebar:
    title: "Phil in the Blank"
    style: "floating"
    search: false
    alignment: "right"
    contents:
      - text: Posts
        file: posts.qmd
      - text: Poems
        file: poems.qmd
      - text: Projects
        file: projects.qmd
      - text: About
        file: index.qmd
      

  favicon: photos/favicon.ico
  twitter-card:
    creator: "@NguyenHPhil"
    card-style: summary_large_image

format:
  html:
    theme: ember.scss
    css: styles.css
